# -*- coding: utf-8 -*-
"""
/***************************************************************************
 RouteNavigator
                                 A QGIS plugin
 Calculo de rutas optimas con los algoritmos de A* y Dijkstra
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-06-03
        copyright            : (C) 2024 by Sergio Acuña
        email                : ssacunav@udistrital.edu.co
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load RouteNavigator class from file RouteNavigator.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .route_navigator import RouteNavigator
    return RouteNavigator(iface)

