# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'route_navigator_dialog_base.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_RouteNavigatorDialogBase(object):
    def setupUi(self, RouteNavigatorDialogBase):
        RouteNavigatorDialogBase.setObjectName("RouteNavigatorDialogBase")
        RouteNavigatorDialogBase.resize(423, 274)
        self.S_groupBox = QtWidgets.QGroupBox(RouteNavigatorDialogBase)
        self.S_groupBox.setGeometry(QtCore.QRect(10, 20, 251, 121))
        self.S_groupBox.setObjectName("S_groupBox")
        self.pushButton_2 = QtWidgets.QPushButton(self.S_groupBox)
        self.pushButton_2.setGeometry(QtCore.QRect(140, 80, 89, 25))
        self.pushButton_2.setObjectName("pushButton_2")
        self.label = QtWidgets.QLabel(self.S_groupBox)
        self.label.setGeometry(QtCore.QRect(10, 40, 111, 17))
        self.label.setObjectName("label")
        self.pushButton = QtWidgets.QPushButton(self.S_groupBox)
        self.pushButton.setGeometry(QtCore.QRect(140, 40, 89, 25))
        self.pushButton.setObjectName("pushButton")
        self.label_2 = QtWidgets.QLabel(self.S_groupBox)
        self.label_2.setGeometry(QtCore.QRect(10, 80, 131, 20))
        self.label_2.setObjectName("label_2")
        self.A_groupBox = QtWidgets.QGroupBox(RouteNavigatorDialogBase)
        self.A_groupBox.setGeometry(QtCore.QRect(10, 150, 401, 101))
        self.A_groupBox.setObjectName("A_groupBox")
        self.pushButton_4 = QtWidgets.QPushButton(self.A_groupBox)
        self.pushButton_4.setGeometry(QtCore.QRect(250, 50, 89, 25))
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_3 = QtWidgets.QPushButton(self.A_groupBox)
        self.pushButton_3.setGeometry(QtCore.QRect(140, 50, 89, 25))
        self.pushButton_3.setObjectName("pushButton_3")
        self.label_4 = QtWidgets.QLabel(self.A_groupBox)
        self.label_4.setGeometry(QtCore.QRect(10, 50, 111, 17))
        self.label_4.setObjectName("label_4")
        self.B_groupBox = QtWidgets.QGroupBox(RouteNavigatorDialogBase)
        self.B_groupBox.setGeometry(QtCore.QRect(279, 19, 131, 121))
        self.B_groupBox.setObjectName("B_groupBox")
        self.pushButton_5 = QtWidgets.QPushButton(self.B_groupBox)
        self.pushButton_5.setGeometry(QtCore.QRect(20, 60, 89, 25))
        self.pushButton_5.setObjectName("pushButton_5")

        self.retranslateUi(RouteNavigatorDialogBase)
        QtCore.QMetaObject.connectSlotsByName(RouteNavigatorDialogBase)

    def retranslateUi(self, RouteNavigatorDialogBase):
        _translate = QtCore.QCoreApplication.translate
        RouteNavigatorDialogBase.setWindowTitle(_translate("RouteNavigatorDialogBase", "Route Navigator"))
        self.S_groupBox.setTitle(_translate("RouteNavigatorDialogBase", "Selección"))
        self.pushButton_2.setText(_translate("RouteNavigatorDialogBase", "Fin"))
        self.label.setText(_translate("RouteNavigatorDialogBase", "Punto de Inicio:"))
        self.pushButton.setText(_translate("RouteNavigatorDialogBase", "Inicio"))
        self.label_2.setText(_translate("RouteNavigatorDialogBase", "Punto de Llegada:"))
        self.A_groupBox.setTitle(_translate("RouteNavigatorDialogBase", "Algoritmo"))
        self.pushButton_4.setText(_translate("RouteNavigatorDialogBase", "Dijkstra"))
        self.pushButton_3.setText(_translate("RouteNavigatorDialogBase", "A*"))
        self.label_4.setText(_translate("RouteNavigatorDialogBase", "Calculo de Ruta:"))
        self.B_groupBox.setTitle(_translate("RouteNavigatorDialogBase", "Borrar Seleccion"))
        self.pushButton_5.setText(_translate("RouteNavigatorDialogBase", "Borrar"))
